const INVESTIGATORS_DATA = [
    { "name": "Roland Banks", "role": "The Fed", "class": "Guardian", "expansion": "Core Set", "willpower": 3, "intellect": 3, "combat": 4, "agility": 2, "health": 9, "sanity": 5 },
    { "name": "Daisy Walker", "role": "The Librarian", "class": "Seeker", "expansion": "Core Set", "willpower": 3, "intellect": 5, "combat": 2, "agility": 2, "health": 5, "sanity": 9 },
    { "name": "Skids OToole", "role": "The Ex-Con", "class": "Rogue", "expansion": "Core Set", "willpower": 2, "intellect": 3, "combat": 3, "agility": 4, "health": 8, "sanity": 6 },
    { "name": "Agnes Baker", "role": "The Waitress", "class": "Mystic", "expansion": "Core Set", "willpower": 5, "intellect": 2, "combat": 2, "agility": 3, "health": 6, "sanity": 8 },
    { "name": "Wendy Adams", "role": "The Urchin", "class": "Survivor", "expansion": "Core Set", "willpower": 4, "intellect": 3, "combat": 1, "agility": 4, "health": 7, "sanity": 7 },
    { "name": "Zoey Samaras", "role": "The Chef", "class": "Guardian", "expansion": "The Dunwich Legacy", "willpower": 4, "intellect": 2, "combat": 4, "agility": 2, "health": 9, "sanity": 6 },
    { "name": "Rex Murphy", "role": "The Reporter", "class": "Seeker", "expansion": "The Dunwich Legacy", "willpower": 3, "intellect": 4, "combat": 2, "agility": 3, "health": 6, "sanity": 9 },
    { "name": "Jenny Barnes", "role": "The Dilettante", "class": "Rogue", "expansion": "The Dunwich Legacy", "willpower": 3, "intellect": 3, "combat": 3, "agility": 3, "health": 8, "sanity": 8 },
    { "name": "Jim Culver", "role": "The Musician", "class": "Mystic", "expansion": "The Dunwich Legacy", "willpower": 4, "intellect": 3, "combat": 2, "agility": 2, "health": 7, "sanity": 8 },
    { "name": "Ashcan Pete", "role": "The Drifter", "class": "Survivor", "expansion": "The Dunwich Legacy", "willpower": 4, "intellect": 2, "combat": 2, "agility": 3, "health": 6, "sanity": 5 },
    { "name": "Lola Hayes", "role": "The Actress", "class": "Neutral", "expansion": "The Path to Carcosa", "willpower": 3, "intellect": 3, "combat": 3, "agility": 3, "health": 6, "sanity": 6 },
    { "name": "Leo Anderson", "role": "The Expedition Leader", "class": "Guardian", "expansion": "The Forgotten Age", "willpower": 4, "intellect": 3, "combat": 4, "agility": 1, "health": 8, "sanity": 6 },
    { "name": "Ursula Downs", "role": "The Explorer", "class": "Seeker", "expansion": "The Forgotten Age", "willpower": 3, "intellect": 4, "combat": 1, "agility": 4, "health": 7, "sanity": 7 },
    { "name": "Finn Edwards", "role": "The Bootlegger", "class": "Rogue", "expansion": "The Forgotten Age", "willpower": 1, "intellect": 4, "combat": 3, "agility": 4, "health": 7, "sanity": 7 },
    { "name": "Father Mateo", "role": "The Priest", "class": "Mystic", "expansion": "The Forgotten Age", "willpower": 4, "intellect": 3, "combat": 2, "agility": 3, "health": 6, "sanity": 8 },
    { "name": "Calvin Wright", "role": "The Haunted", "class": "Survivor", "expansion": "The Forgotten Age", "willpower": 0, "intellect": 0, "combat": 0, "agility": 0, "health": 6, "sanity": 6 },
    { "name": "Carolyn Fern", "role": "The Psychologist", "class": "Guardian", "expansion": "The Circle Undone", "willpower": 3, "intellect": 4, "combat": 2, "agility": 2, "health": 6, "sanity": 9 },
    { "name": "Joe Diamond", "role": "The Private Eye", "class": "Seeker", "expansion": "The Circle Undone", "willpower": 2, "intellect": 4, "combat": 4, "agility": 2, "health": 8, "sanity": 6 },
    { "name": "Preston Fairmont", "role": "The Millionaire", "class": "Rogue", "expansion": "The Circle Undone", "willpower": 1, "intellect": 1, "combat": 1, "agility": 1, "health": 7, "sanity": 7 },
    { "name": "Diana Stanley", "role": "The Redeemed Cultist", "class": "Mystic", "expansion": "The Circle Undone", "willpower": 1, "intellect": 3, "combat": 3, "agility": 3, "health": 7, "sanity": 8 },
    { "name": "Rita Young", "role": "The Athlete", "class": "Survivor", "expansion": "The Circle Undone", "willpower": 3, "intellect": 2, "combat": 3, "agility": 5, "health": 9, "sanity": 5 },
    { "name": "Marie Lambeau", "role": "The Entertainer", "class": "Mystic", "expansion": "The Circle Undone", "willpower": 4, "intellect": 4, "combat": 1, "agility": 3, "health": 6, "sanity": 8 },
    { "name": "Sister Mary", "role": "The Nun", "class": "Guardian", "expansion": "The Innsmouth Conspiracy", "willpower": 4, "intellect": 2, "combat": 3, "agility": 3, "health": 5, "sanity": 9 },
    { "name": "Amanda Sharpe", "role": "The Student", "class": "Seeker", "expansion": "The Innsmouth Conspiracy", "willpower": 2, "intellect": 2, "combat": 2, "agility": 2, "health": 7, "sanity": 7 },
    { "name": "Trish Scarborough", "role": "The Spy", "class": "Rogue", "expansion": "The Innsmouth Conspiracy", "willpower": 2, "intellect": 4, "combat": 2, "agility": 4, "health": 8, "sanity": 6 },
    { "name": "Dexter Drake", "role": "The Magician", "class": "Mystic", "expansion": "The Innsmouth Conspiracy", "willpower": 5, "intellect": 2, "combat": 3, "agility": 2, "health": 6, "sanity": 8 },
    { "name": "Silas Marsh", "role": "The Sailor", "class": "Survivor", "expansion": "The Innsmouth Conspiracy", "willpower": 2, "intellect": 2, "combat": 4, "agility": 4, "health": 9, "sanity": 5 },
    { "name": "Daniela Reyes", "role": "The Mechanic", "class": "Guardian", "expansion": "Edge of the Earth", "willpower": 4, "intellect": 1, "combat": 5, "agility": 2, "health": 8, "sanity": 6 },
    { "name": "Norman Withers", "role": "The Astronomer", "class": "Seeker", "expansion": "Edge of the Earth", "willpower": 4, "intellect": 5, "combat": 2, "agility": 1, "health": 6, "sanity": 8 },
    { "name": "Monterey Jack", "role": "The Archaeologist", "class": "Rogue", "expansion": "Edge of the Earth", "willpower": 1, "intellect": 4, "combat": 2, "agility": 5, "health": 8, "sanity": 6 },
    { "name": "Lily Chen", "role": "The Martial Artist", "class": "Mystic", "expansion": "Edge of the Earth", "willpower": 3, "intellect": 2, "combat": 4, "agility": 3, "health": 7, "sanity": 7 },
    { "name": "Bob Jenkins", "role": "The Salesman", "class": "Survivor", "expansion": "Edge of the Earth", "willpower": 2, "intellect": 4, "combat": 1, "agility": 3, "health": 6, "sanity": 8 },
    { "name": "Carson Sinclair", "role": "The Butler", "class": "Guardian", "expansion": "The Scarlet Keys", "willpower": 2, "intellect": 2, "combat": 2, "agility": 2, "health": 6, "sanity": 6 },
    { "name": "Vincent Lee", "role": "The Doctor", "class": "Seeker", "expansion": "The Scarlet Keys", "willpower": 3, "intellect": 4, "combat": 3, "agility": 2, "health": 9, "sanity": 5 },
    { "name": "Kymani Jones", "role": "The Security Consultant", "class": "Rogue", "expansion": "The Scarlet Keys", "willpower": 3, "intellect": 2, "combat": 2, "agility": 5, "health": 8, "sanity": 6 },
    { "name": "Amina Zidane", "role": "The Operator", "class": "Mystic", "expansion": "The Scarlet Keys", "willpower": 3, "intellect": 3, "combat": 3, "agility": 3, "health": 5, "sanity": 9 },
    { "name": "Darrell Simmons", "role": "The Photographer", "class": "Survivor", "expansion": "The Scarlet Keys", "willpower": 2, "intellect": 5, "combat": 1, "agility": 4, "health": 6, "sanity": 8 },
    { "name": "Charlie Kane", "role": "The Politician", "class": "Neutral", "expansion": "The Scarlet Keys", "willpower": 1, "intellect": 1, "combat": 1, "agility": 1, "health": 6, "sanity": 6 },
    { "name": "Wilson Richards", "role": "The Handyman", "class": "Guardian", "expansion": "The Feast of Hemlock Vale", "willpower": 3, "intellect": 3, "combat": 4, "agility": 2, "health": 8, "sanity": 6 },
    { "name": "Kate Winthrop", "role": "The Scientist", "class": "Seeker", "expansion": "The Feast of Hemlock Vale", "willpower": 2, "intellect": 4, "combat": 2, "agility": 4, "health": 6, "sanity": 8 },
    { "name": "Alessandra Zorzi", "role": "The Countess", "class": "Rogue", "expansion": "The Feast of Hemlock Vale", "willpower": 3, "intellect": 4, "combat": 2, "agility": 4, "health": 7, "sanity": 7 },
    { "name": "Kohaku Narukami", "role": "The Folklorist", "class": "Mystic", "expansion": "The Feast of Hemlock Vale", "willpower": 4, "intellect": 4, "combat": 3, "agility": 1, "health": 6, "sanity": 8 },
    { "name": "Hank Samson", "role": "The Farmhand", "class": "Survivor", "expansion": "The Feast of Hemlock Vale", "willpower": 3, "intellect": 1, "combat": 5, "agility": 3, "health": 5, "sanity": 5 },
    { "name": "Marion Tavares", "role": "The Trawler", "class": "Guardian", "expansion": "The Drowned City", "willpower": 3, "intellect": 2, "combat": 4, "agility": 3, "health": 8, "sanity": 6 },
    { "name": "Lucius Galloway", "role": "The Poet", "class": "Seeker", "expansion": "The Drowned City", "willpower": 4, "intellect": 4, "combat": 2, "agility": 3, "health": 7, "sanity": 7 },
    { "name": "Michael McGlen", "role": "The Gangster", "class": "Rogue", "expansion": "The Drowned City", "willpower": 3, "intellect": 2, "combat": 5, "agility": 2, "health": 9, "sanity": 5 },
    { "name": "Agatha Crane", "role": "The Parapsychologist", "class": "Mystic", "expansion": "The Drowned City", "willpower": 4, "intellect": 4, "combat": 1, "agility": 3, "health": 6, "sanity": 8 },
    { "name": "Agatha Crane", "role": "The Parapsychologist", "class": "Seeker", "expansion": "The Drowned City", "willpower": 4, "intellect": 4, "combat": 1, "agility": 3, "health": 6, "sanity": 8 },
    { "name": "Gloria Goldberg", "role": "The Writer", "class": "Mystic", "expansion": "The Drowned City", "willpower": 5, "intellect": 4, "combat": 2, "agility": 1, "health": 6, "sanity": 9 },
    { "name": "George Barnaby", "role": "The Lawyer", "class": "Survivor", "expansion": "The Drowned City", "willpower": 2, "intellect": 4, "combat": 2, "agility": 4, "health": 6, "sanity": 8 },
    { "name": "Nathaniel Cho", "role": "The Boxer", "class": "Guardian", "expansion": "Investigator Starter Deck", "willpower": 3, "intellect": 2, "combat": 5, "agility": 2, "health": 9, "sanity": 6 },
    { "name": "Harvey Walters", "role": "The Professor", "class": "Seeker", "expansion": "Investigator Starter Deck", "willpower": 4, "intellect": 5, "combat": 1, "agility": 2, "health": 7, "sanity": 8 },
    { "name": "Winifred Habbamock", "role": "The Aviatrix", "class": "Rogue", "expansion": "Investigator Starter Deck", "willpower": 1, "intellect": 3, "combat": 3, "agility": 5, "health": 8, "sanity": 7 },
    { "name": "Jacqueline Fine", "role": "The Psychic", "class": "Mystic", "expansion": "Investigator Starter Deck", "willpower": 5, "intellect": 3, "combat": 2, "agility": 2, "health": 6, "sanity": 9 },
    { "name": "Stella Clark", "role": "The Letter Carrier", "class": "Survivor", "expansion": "Investigator Starter Deck", "willpower": 3, "intellect": 2, "combat": 3, "agility": 4, "health": 8, "sanity": 8 }
];

window.INVESTIGATORS_DATA = INVESTIGATORS_DATA;
